name: CI

on: [push]

jobs:
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Execute curl command
        id: test
        uses: lcherone/gh-actions/curl@master
        with:
          args: -X POST -H "Content-Type:application/json" -H "accept:application/json" -d '{"token":"12345","action":"ci"}' https://httpbin.org/post

      - name: Get the output
        run: echo "${{ steps.test.outputs.stdout }}"
